#!/usr/bin/env bash

### ------------------------------------------------------------------------
### name:       bekap1_en_lh.sh
### author:     RgregoR
### date:       januar 2023
### UPDATE:		20230111
### ------------------------------------------------------------------------


function tms() {
    echo -n "[ $(date +%Y%m%d_%H%M%S) ] "
}


tms; echo "Starting $0 ..."

# *************************************************************
# VARIABLES
# =========

# source folder:
gr_FROMBIN=$HOME/majstaf/coding
gr_FROMMTS=$HOME/majstaf/metsys_en
gr_FROMRCS=$HOME/majstaf/majrcs
gr_FROMBRC=$HOME/.[a-zA-Z0-9]*
gr_FROMSZN=$HOME/majstaf/seznami
gr_FROMCIG='/c/Users/gregor.redelonghi/majstaf/majprogs/cygwin64'
# destination folder
gr_TOF="/c/Users/gregor.redelonghi/majstaf/bekap_en_all"
gr_LOG="/c/Users/gregor.redelonghi/majstaf/bekap_en_all/bekap_en.log"

# datestamp:
gr_DATE=$(date +%Y%m%d_%H%M%S)

#archive:
gr_CURRCDNG="bckp_cdng_en_${gr_DATE}.tar.gz"
gr_CURRMTS="bckp_mtss_en_${gr_DATE}.tar.gz"
gr_CURRRCS="bckp_rcs_en_${gr_DATE}.tar.gz"
gr_CURRSZN="bckp_szn_en_${gr_DATE}.tar.gz"
gr_CURRBRC="bckp_brc_en_${gr_DATE}.tar.gz"
gr_CURRBAT="bckp_bat_en_${gr_DATE}.tar.gz"

# TEST if archive file exists:
if [ ! -e ${gr_TOF} ]; then
    echo "NO Destination!"
    exit 1
fi

if [ "$(ls -A ${gr_TOF}/bckp*)" ]; then
	tms; echo "${gr_TOF}/ is NOT empty!"
	echo
	tms; echo "Removing files from ${gr_TOF}/ ..."
	rm -v ${gr_TOF}/bckp*
else
	tms; echo "${gr_TOF}/ is empty ..."
fi

# Ask for confirmation:
### read -p "Press any key to CREATE archives or [ctrl+c] to quit"

# creating an archive:
echo
tms; echo "Creating archive: ${gr_TOF}/${gr_CURRCDNG} "
tar -czf ${gr_TOF}/${gr_CURRCDNG} -C $HOME/majstaf coding

tms; echo "Creating archive: ${gr_TOF}/${gr_CURRMTS}"
tar -czf ${gr_TOF}/${gr_CURRMTS} -C $HOME/majstaf metsys_en

tms; echo "Creating archive: ${gr_TOF}/${gr_CURRRCS}"
tar -czf ${gr_TOF}/${gr_CURRRCS} -C $HOME/majstaf majrcs

tms; echo "Creating archive: ${gr_TOF}/${gr_CURRSZN}"
tar -czf ${gr_TOF}/${gr_CURRSZN} -C $HOME/majstaf seznami

tms; echo "Creating archive: ${gr_TOF}/${gr_CURRBRC}"
cd $HOME && find -type f -iname ".*" | tar -czf ${gr_TOF}/${gr_CURRBRC} -T -

tms; echo "Creating archive: ${gr_TOF}/${gr_CURRBAT}"
cd ${gr_FROMCIG} && find -maxdepth 1 -type f -iname "*.bat*" | tar -czf ${gr_TOF}/${gr_CURRBAT} -T -


echo
tms; echo "successfully backed up MTSS, CDNG, RCS, SZN, BRC and BAT archives to ${gr_TOF}" | tee -a ${gr_LOG} # append to log

