#! /usr/bin/env bash

majbin_src=~/majstaf_en/majbin_en
majbin_dst=~/majstaf_en/engit/majbin_en

fjls=$(diff -q ${majbin_src}/ ${majbin_dst}/ | grep -iv common |grep -iv .git | cut -d' ' -f3- | sed 's/: //' | fzf -m --reverse)


if [ "x${fjls[0]}" == "x" ]; then
	echo "No files found/selected"
	exit
fi

SRC=$(echo ${majbin_src} | sed "s/\/home\/gregor.redelonghi\/majstaf_en\///")
DST=$(echo ${majbin_dst} | sed "s/\/home\/gregor.redelonghi\/majstaf_en\///")

echo -e "Files to be copied from [${SRC}/] to [${DST}]:"
i=0
for FJL in ${fjls[@]}; do
	let i=$i+1
	if [ $i -lt 10 ]; then
		i="0${i}"
	fi
	echo -e "\t${i} - $(basename ${FJL})"
done
echo ""

read -p "[y/Y] to procede [Any other key to quit] " choice

if [ $choice == "y" ] || [ $choice == "Y" ]; then
	for FJL in ${fjls[@]}; do
		cp -iv ${FJL} ${majbin_dst}/
	done
else
	echo "quit"
	exit
fi

