#! /usr/bin/env bash
# last change 20240229 (en)

CURRDIR=$PWD
MJSTFN=${HOME}/majstaf_en
MJSTFN_G=${MJSTFN}/engit

cd ${MJSTFN_G}/dotfiles_en
	echo "[INFO] diffs: dotfiles_en ..."
for FFF in $(ls -1A); do diff -qr $FFF ${HOME}/${FFF} 2>/dev/null | grep -iv 'only'; done
echo "---"

for checkeddir in majbin_en majrcs_en metsys_en; do
	cd ${MJSTFN_G}/${checkeddir}
	echo "[INFO] diffs: ${checkeddir} ..."
	for FFF in $(ls -1); do diff -qr $FFF ${MJSTFN}/${checkeddir}/${FFF} | grep -iv 'only'; done
	echo "---"
	cd $HOME
done

cd ${CURRDIR}

