#! /usr/bin/env bash
# filename: majapps-launch.sh
# 20250917 (en)
# 20250919 (en) -- added runff var for firefox path
# last: 20250919 (en)

runff="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe"


declare -A apps=(["Firefox"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe" \
                 ["MS Edge"]="$(cygpath -w /c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe)" \
                 ["Google Chrome"]="C:\Program Files\Google Chrome Portable\GoogleChromePortable.exe" \
                 ["MS Calc"]="/c/Windows/System32/calc.exe" \
                 ["Acrobat Reader"]="C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe"
                 ["AutoCAD 2024"]=""
                 ["Explorer++"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/Explorerpp/Explorer++.exe" \
                 ["Notepad++"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/Notepad++/notepad++.exe" \
                 ["Super Launcher"]="c:\Users\Public\below average\Super Launcher\SuperLauncher.exe" \
                 ["Nukleus (EN)"]="" \
                 ["Razvojne Rešitve (EN)"]="")

# echo "apps values only: ${apps[@]}"
# echo "apps keys only:   ${!apps[@]}"
# echo "apps length:      ${#apps[@]}"

selection=$(for app in "${!apps[@]}"; do echo "$app"; done | fzf -e --reverse +c -i --prompt="launch: ")

if [ "x${selection}" == "x" ]; then
	echo "[ERROR] no selection"
	exit
fi

# RUN
if [ "${selection}" == "AutoCAD 2024" ]; then
	cygstart "C:\Program Files\Autodesk\AutoCAD 2024\acad.exe"  /product ACAD /language "en-US" &>/dev/null
elif [ "${selection}" == "Nukleus (EN)" ]; then
	${runff} "http://jpe-nukleus.jhl.si/PassAuth/AutoAuth.aspx?ReturnUrl=/nukleus/profile.aspx?id=Energetika@Ljubljana"
elif [ "${selection}" == "Razvojne Rešitve (EN)" ]; then
	${runff} "https://jpe-arcgis-port.jhl.si/arcgis/apps/webappviewer/index.html?id=b7ec743d0247439fbe941cb6187fa094"
else
	cygstart "${apps["${selection}"]}" &>/dev/null
fi

#############################################
# TODO
# gr_verzija=" [ verzija-en - last update: 202401119 ] "
# gr_izbira=""
# gr_novapot="/c/users/gregor.redelonghi/majstaf_en/r.gregor.en/orodjarna/ukazi/podukazi"
# gr_OFPOT='/c/Program Files/Microsoft Office/root/Office16'
# gr_GGL="/c/Users/gregor.redelonghi/AppData/Local/Google/Chrome/Application/chrome.exe"
# gr_IE=/c/Program\ Files/Internet\ Explorer/iexplore.exe
# gr_FF=/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe
# gr_MSE=/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe
#
# cygstart "${gr_OFPOT}/EXCEL.EXE"
# cygstart "${gr_OFPOT}/WINWORD.EXE"
# cygstart "${gr_OFPOT}/POWERPNT.EXE"
# cygstart "${gr_OFPOT}/OUTLOOK.EXE"
# cygstart /c/Windows/System32/calc.exe
# cygstart /c/Program\ Files\ \(x86\)/Adobe/Acrobat\ Reader\ DC/Reader/AcroRd32.exe
# ${gr_novapot}/clc.bat
# cygstart "C:\Program Files\Autodesk\AutoCAD 2024\acad.exe"  /product ACAD /language "en-US"
# cygstart "C:\Program Files\Autodesk\AutoCAD 2024\acad.exe" /b "C:\Program Files\SL-King\Sewer+\Sewer+Load.scr"
# cygstart explorer /E,"$(cygpath -w /c/users/gregor.redelonghi/${CURRYR})"
# cygstart /c/Users/gregor.redelonghi/majstaf_en/majprogs_en/MultiCommander_X64/MultiCommander.exe
# cygstart "$gr_IE"
# cygstart "${gr_MSE}" www.google.com
# cygstart /c/WINDOWS/system32/ssmypics.scr /s
# cygstart $gr_FF "http://jpe-nukleus.jhl.si/PassAuth/AutoAuth.aspx?ReturnUrl=/nukleus/profile.aspx?id=Energetika@Ljubljana"
# cygstart '/c/Program Files/Google Chrome Portable/GoogleChromePortable.exe'
# cygstart $gr_FF
# cygstart explorer /E, $(cygpath -w /c/users/gregor.redelonghi/${CURRYR})
# cygstart /c/users/gregor.redelonghi/majstaf_en/majprogs_en/cygwin64/bin/mintty.exe -p 40,40 -s 200,50 -
# cygstart /c/Users/gregor.redelonghi/majstaf_en/majprogs_en/CodeBlocks/codeblocks.exe
# cygstart "$(cygpath -w "/c/Users/Public/below average/Super Launcher/SuperLauncher.exe")"
# cygstart /c/WINDOWS/System32/rundll32.exe user32.dll LockWorkStation
# cygstart /c/WINDOWS/System32/rundll32.exe  shell32.dll,Control_RunDLL hotplug.dll
