#! /usr/bin/env bash

# former left nohup.out file
# nohup /usr/bin/mintty -e /usr/bin/bash -c "~/majstaf/majbin/BrthReminder/BrthReminder_c_color.exe;cd;bash" 2> /dev/null

# 20240627
nohup /usr/bin/mintty -e /usr/bin/bash -c "~/majstaf/majbin/BrthReminder/BrthReminder_c_color.exe;cd;bash" >/dev/null 2>&1 &

