#!/bin/bash

### ------------------------------------------------------------------------
### name:       np.sh
### author:     RgregoR
### date:       december, 2014
### ------------------------------------------------------------------------
###  script that starts notepad++ with or without parameter (file to open)
###  
### ------------------------------------------------------------------------

# function usage
grf_usage () {
cat <<USAGE
+------------------------------------------------------------------------+
| Usage:                                                                 |
| Script that starts notepad++ with or without parameter (file to open): |
| a.) np          just starts blank notepad++                            |
| b.) np <file>   starts notepad++ with a file                           |
+------------------------------------------------------------------------+
USAGE
}


gr_NPPPTH='/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/Notepad++'
# Testing if an argument is present
gr_maxarg=1
if [ $# -gt ${gr_maxarg} ]; then

    clear
    echo "Too many arguments - only one or zero!"
    grf_usage
    echo
    read -p "Press any key to exit!"
    exit 1

elif [ $# -eq 1 ]; then

    cygstart ${gr_NPPPTH}/notepad++.exe $(cygpath -w $(readlink -f "$1"))

else

    cygstart ${gr_NPPPTH}/notepad++.exe

fi


























