#! /usr/bin/env bash
# risbe_join

if [ $# -eq 1 ]; then
	OUTPUT=$1
else
	OUTPUT="_RISBE.pdf"
fi

if [ -f $OUTPUT ]; then
	echo "$OUTPUT already exists. Supply another filename as argumet"
	exit
fi

FJLS=$(ls -1 0*.pdf)
java -jar $(cygpath -w "/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/pdftk-all.jar") $(echo "$FJLS" |tr '\n' ' ') cat output ${OUTPUT}


