#! /usr/bin/env bash

curr_yr=$(date +"%Y")
dest="/c/Users/gregor.redelonghi/${curr_yr}/_${curr_yr}_1_PROJEKTI"

if [ $# -ne 1 ]; then
	echo "Usage: $0 [date in format \"YYYYmmdd\"]"
	echo ""
	exit 1
fi



showdate=$1

echo -e "VN-s in ${dest} from date ${showdate}:\n---"
cd $dest
find -newermt "${showdate} 07:00:00" | grep "VN_" | cut -d'/' -f2 | sort | uniq

