#! /usr/bin/env bash

unset list
list=()

DANES=$(date +"%Y%m%d")
ZDAJ=$(date +"%H")
URA=8
SRC=${KNOWLEDGEBASE:-/home/gregor.redelonghi/majstaf_en/engit/knowledgedb}

if [ $# -eq 1 ]; then
	if [ $((${ZDAJ} - $1)) -le 0  ]; then
		echo "Out of time range!"
		exit
	fi
	URA=$1
fi

echo -e "\nGetting today's entries:"
echo -e "\tin \"${SRC}\""
echo -e "\tafter: ${URA}:00:00 on $(date +%d/%m/%Y)\n"
read -p "Continue?"

readarray -t -O "${#list[@]}" list < <(find ${SRC} -newermt "${DANES} ${URA}:00:00" -type f | grep -v '\.git')

if [ ${#list[@]} -le 0 ]; then
	echo "[INF] No files found"
	exit
fi

for (( i=0; i<${#list[@]}; i++)); do
	echo "${list[$i]}"
done | fzf -m --reverse | xargs -ro vim -pM

