#! /usr/bin/env bash
# V2

unset list
list=()

DANES=$(date +"%Y%m%d")
ZDAJ=$(date +"%H")
# URA=8
SRC=${KNOWLEDGEBASE:-/home/gregor.redelonghi/majstaf_en/engit/knowledgedb}

if [ $# -eq 1 ]; then
	URA=$1
	DEJT=${DANES}
	if [ $((${ZDAJ} - ${URA})) -le 0  ]; then
		echo "[ERROR]Out of time range!"
		exit
	fi
elif [ $# -eq 2 ]; then
	DEJT=$1
	URA=$2
	if [ $((${DEJT} - ${DANES})) -gt 0 ]; then
		echo "[ERROR] Wrong date"
		exit
	fi
	if [ $((${DANES} - ${DEJT})) -gt 0 ]; then
		ZDAJ=24
	fi
	if [ $((${ZDAJ} - ${URA})) -lt 0  ]; then
		echo "[ERROR] Out of time range!"
		exit
	fi
else
	URA=8
	DEJT=${DANES}
fi

echo -e "\nGetting today's entries:"
echo -e "\tin \"${SRC}\""
echo -e "\tafter: ${URA}:00:00 on ${DEJT}\n"
read -p "Continue?"

readarray -t -O "${#list[@]}" list < <(find ${SRC} -newermt "${DEJT} ${URA}:00:00" -type f | grep -v '\.git')

if [ ${#list[@]} -le 0 ]; then
	echo "[INFO] No files found"
	exit
fi

# for (( i=0; i<${#list[@]}; i++)); do
# 	echo "${list[$i]}"
# done | fzf -m --reverse | xargs -ro vim -pM

fjls=$(for (( i=0; i<${#list[@]}; i++)); do
	echo "${list[$i]}"
done | fzf -m --reverse)

if [ "x${fjls[0]}" == "x" ]; then
	echo "[INFO] No files selected"
	exit
fi

for FJL in $(echo ${fjls[@]}); do echo $FJL; done | xargs -ro vim -pM
