#! /usr/bin/env bash

###  EN-proxy ...
# prx_ip=172.17.3.64
prx_ip=10.91.8.21
export http_proxy=http://${prx_ip}:80/
export ftp_proxy=ftp://${prx_ip}:8021/
export https_proxy=http://${prx_ip}:80/

dumplist="$HOME/majstaf/majbin/lynxdump/multi-dump-list.dat"

if [ $# -eq 1 ]; then
	gr_name=$1
elif [ $# -eq 2 ]; then
	gr_seznam=$1
	if [ ! -f $gr_seznam ]; then
		gr_seznam=${dumplist}
		echo "No such file. Destination: ${dumplist}"
	fi
	gr_name=$2
else
	echo -e "Usage:\n\t$(basename $0) <list> <name>"
	echo -e "   or:\n\t$(basename $0) [default-list] <name>"
	echo -e ""
	exit
fi

gr_dest="$PWD"
gr_dejt=$(date +%Y%m%d)
gr_filename=${gr_name}-multyf-${gr_dejt}.txt

# destination ...
gr_goto="${PWD}"
echo "Destination: ${gr_goto}/${gr_filename}"

# If OK pres any key, else ctrl-c ...
read -p "Continue ?"
cd $gr_goto
touch ${gr_filename}

echo "filename: ${gr_filename}" >> ${gr_filename}

for FFF in $(cat ${gr_seznam}); do echo "inserting $FFF into ${gr_filename}"; done
for FFF in $(cat ${gr_seznam}); do echo -e "$FFF\n" >> ${gr_filename}; lynx -dump -width=110 $FFF >> ${gr_filename}; echo -e "\n\n\n---" >> ${gr_filename}; done

echo
echo 'DONE!'
echo

