#! /usr/bin/env bash

### Name:	drpbx-rclone-SKUPNI2-R-L.sh
### Author:	RgregoR
### Date:	20201112
### Decription:
### rclone copy gLocal to gRemote
### 
### 

gLocal=$(cygpath -w "/c/Users/gregor.redelonghi/majstaf_en/drpbx-en/SKUPNI")
gRemote="dropbox:SKUPNI"

function update() {
    gFrom=$1
    gTo=$2
    echo "Updating remote ${gFrom} to local ${gTo}"
    /usr/local/bin/rclone -v sync ${gFrom} ${gTo}


    # dry-run
    # /usr/local/bin/rclone -v -n sync ${gFrom} ${gTo}
    
    if [ $? == 0 ]; then
        echo "Done."
    else
        echo "Something went wrong!"
        exit 1
    fi
}

update ${gRemote} ${gLocal}

