#! /bin/bash
### script that replaces spaces with hypens in filenames ...

# set IFS to newline '\n'
nifs()	{
	IFS=$'\n'
}

# set IFS to orginal ' \t\n'
oifs() {
	IFS=$' \t\n'
}

nifs

if [ $# -ne 1 ]; then
    echo "Usage: $0 [single-filename-with-spaces]"
    exit
fi

inputf=$1

if [ ! -f ${inputf} ]; then
    echo "No such file: \"${inputf}\"!"
    exit 1
fi

# source_path=$(realpath $(dirname ${inputf}))
source_file=$(realpath ${inputf})
echo "source_file: $source_file"

renamed=$(echo ${source_file} | tr ' ' '-')
echo "renamed: ${renamed}"

read -p "Continue renaming?"
# echo "mv -vvv ${source_file} ${renamed}"

mv -vvv "${source_file}" "${renamed}"
oifs
