#! /usr/bin/env bash

### Name:	megamz-rclone-ptn2-R-L.sh
### Author:	RgregoR
### Date:	20201111
### Decription:
### sync local ODPRTO/_PYTHON to dropbox(EN) with rclone
### 
### 


gLocal=$(cygpath -w "/c/Users/gregor.redelonghi/majstaf/MEGA/ODPRTO/_PYTHON") 
gRemote="meganz:ODPRTO/_PYTHON"

function update() {
    gFrom=$1
    gTo=$2
    echo "Updating remote ${gFrom} to local ${gTo}"
    /usr/local/bin/rclone -v sync ${gFrom} ${gTo}

    # dry-run
    # /usr/local/bin/rclone -v -n sync ${gFrom} ${gTo}
    
    if [ $? == 0 ]; then
        echo "Done."
    else
        echo "Something went wrong!"
        exit 1
    fi
}

update ${gRemote} ${gLocal}
