#! /usr/bin/env bash

### Name:	megamz-rclone-ptn1-L-R.sh
### Author:	RgregoR
### Date:	20201111
### Decription:
### rclone copy gRemote to gLocal
### 
### 


gLocal=$(cygpath -w "/c/Users/gregor.redelonghi/majstaf/MEGA/ODPRTO/_PYTHON")
gRemote="meganz:ODPRTO/_PYTHON"

function update() {
    gFrom=$1
    gTo=$2
    echo "Updating local ${gFrom} to remote ${gTo}"
    /usr/local/bin/rclone -v sync ${gFrom} ${gTo}

    # dry-run
    # /usr/local/bin/rclone -v -n sync ${gFrom} ${gTo}
    
    if [ $? == 0 ]; then
        echo "Done."
    else
        echo "Something went wrong!"
        exit 1
    fi
}

update ${gLocal} ${gRemote}