#! /usr/bin/env bash
# flename: engt-check-reports
# last change: 20250827

echo "[INFO] checking reports for git staus commands ..."
cat $GIT_STATUS_REPORTS
echo "---"
echo "[INFO] checking reports for git test push commands ..."
cat $GIT_TPUSH_REPORTS
echo "---"
