#! /usr/bin/env bash
# filename: engt-testpush
# 20241216: store output of cmd into array instead of external file
# 20241218: c-style for loop
# 20250415: update to directories and filenames changes
# 20250827: added $GIT_STATUS_REPORTS filename to store reports
# last change: 20250827

# COLOR_SET="\e[1;94m"
# COLOR_SET="\e[1;34m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
HST="en"
# DEST=${HOME}/majstaf/${HST}git
DEST=${HOME}/majstaf/${HST}git
> $GIT_TPUSH_REPORTS

unset output
unset report

output=()
report=()

CURRDIR=$PWD
cd ${DEST}

echo "========================================"
echo "[INFO] running engt-testpush ..."
echo "========================================"
for DDD in $(find * -maxdepth 0 -type d); do
	printf "${COLOR_SET}"
	echo "***    git testpush in: ${DDD} ..."
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null
	readarray -t output < <(~/.local/bin/ghgl-testpush-${HST})
	for (( i=0; i<${#output[@]}; i++)); do
		if [[ "${output[$i]}" =~ "PULL" ]]; then
			msg="$(echo -e "[REPORT] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE")"
			readarray -t -O "${#report[@]}" report < <(echo -e "$msg")
			echo -e ${output[$i]}
			break
		else
			echo -e ${output[$i]}
		fi
	done
	cd ..
done

printf "${COLOR_SET}"
if [ ${#report[@]} -gt 0 ]; then
	echo
	for (( j=0; j<${#report[@]}; j++)); do
		echo "*** ${report[$j]} ***" | tee -a $GIT_TPUSH_REPORTS
	done
else
	echo
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"

cd ${CURRDIR}

echo ""

