#! /usr/bin/env bash
# filename: engttestpush
# last edit: 20240228_en

CURRDIR=$PWD
cd ~/majstaf_en/engit/
for DDD in $(find * -maxdepth 0 -type d); do
	echo ""
	echo "*** git testpush in ${DDD} ... ***"
	cd $DDD &>/dev/null && ~/.local/bin/ghgltestpush_en && cd ..
# echo -e "\n---"
done

cd ${CURRDIR}

