#! /usr/bin/env bash
# filename: engtstst.sh
# last edit: 20240227_en

CURRDIR=$PWD
cd ~/majstaf_en/engit/
for DDD in $(find * -maxdepth 0 -type d | grep -v 'vlpprs_en'); do
	echo "[INFO] checking git status in ${DDD} ..."
	cd $DDD
	/usr/bin/git status
	cd ..
	echo -e "\n---"
done
cd ${CURRDIR}


VLPEN="~/majstaf_en/engit/vlpprs_en"
echo "[INFO] checking git status in ${VLPEN} ..."
NVOL='/usr/bin/git --git-dir=/home/gregor.redelonghi/majstaf_en/engit/vlpprs_en --work-tree=/c/Users/gregor.redelonghi/majstaf_en/en_staf/majvolpejprs'
${NVOL} status
echo -e "\n---"

