#! /usr/bin/env bash
# gadd_gcmt_en
# last change: 20240912

gcmd="/usr/bin/git add --verbose ."
gcmt="${HOME}/.local/bin/gcommit_timestamp_en"


# display and run commands
echo -en "running: ${gcmd}\n" && ${gcmd}
echo
echo -en "running: ${gcmt}\n" && ${gcmt}

