#! /usr/bin/env bash
# gcommit_timestamp_en
# last change: 20240823

cmd="/usr/bin/git commit"

if [ $# -eq 1 ]; then
	if [ $1 == "-a" ]; then
		echo "/usr/bin/git commit -a"
		read -p "OK?"
		$cmd -a
		exit
	else
		msg=$1
	fi
else
	msg="update"
fi

tmpstmp=$(date +"%Y%m%d_%H%M")_en
desc="$msg ${tmpstmp}"

echo "/usr/bin/git commit -m \"$desc\""
read -p "OK?"
$cmd -m "$desc"

