#! /usr/bin/env bash

if [ $# -eq 1 ]; then
	msg=$1
else
	msg="update"
fi

tmpstmp=$(date +"%Y%m%d_%H%M")_en
desc="$msg ${tmpstmp}"

# /usr/bin/git commit --dry-run -m "$desc"
echo "/usr/bin/git commit -m \"$desc\""
/usr/bin/git commit -m "$desc"

