#! /usr/bin/env bash

cmd="/usr/bin/git commit"

if [ $# -eq 1 ]; then
	if [ $1 == "-a" ]; then
		echo "/usr/bin/git commit -a"
		read -p "OK?"
		$cmd -a
		exit
	else
		msg=$1
	fi
else
	msg="update"
fi

tmpstmp=$(date +"%Y%m%d_%H%M")_en
desc="$msg ${tmpstmp}"

# /usr/bin/git commit --dry-run -m "$desc"
echo "/usr/bin/git commit -m \"$desc\""
read -p "OK?"
$cmd -m "$desc"

