#! /usr/bin/env bash
# ghglpush_en
# last change: 20240821_en

rmts=( $(git remote) )

for rmt in "${rmts[@]}"
do
	echo "[INFO] git push to: $(git remote get-url ${rmt}) ..."
	git push ${rmt} main
	echo "---"
done

