#! /usr/bin/env bash
# ghgltestpush_en
# last change: 202400301_en

rmts=( $(git remote) )

COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"

for rmt in "${rmts[@]}"
do
	echo -n "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
	OUTPUT=$(/usr/bin/git push --dry-run ${rmt} main)
	echo $OUTPUT | grep 'main' &> /dev/null
	if [[ $? -ne 0 ]]; then
		printf "${COLOR_SET}"
		echo "NEED TO PUSH!!\n"
		printf "${COLOR_RESET}"
		/usr/bin/git push --dry-run ${rmt} main
	else
		echo " nothig to push!"
	fi
done

