#! /usr/bin/env bash

rmts=( $(git remote) )

for rmt in "${rmts[@]}"
do
	# echo "[INFO] checking if 'main' and '${rmt}/main' are in sync ..."
	echo "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
	git push --dry-run ${rmt} main
	echo ""
done

