#! /usr/bin/env bash

if [ $# -ne 1 ]; then
	echo -e "Usage: $0 <file_name>\n\n"
	exit
else
	fname=$1
	usr=en
fi

curdir="$(basename $PWD)"
# destdir="$(echo $PWD | sed "s:majstaf_en:majstaf_en/${usr}git:")"
destdir="$(echo $PWD | sed "s:majstaf_${usr}/\(.*\):majstaf_${usr}/${usr}git/\1:" | sed "s:\.config:majstaf_${usr}/${usr}git/dotfiles_${usr}/.config:")"

read -p "cp -i ./${fname} ${destdir}/${fname} ?"
cp -v ./${fname} ${destdir}/${fname}

