#! /usr/bin/env bash
# filename: grefresh-fjl-to-git-repo
# 20241216

if [ $# -ne 1 ]; then
	echo -e "Usage: $0 <file-name>\n\n"
	exit
else
	fname=$1
	usr=en
fi

curdir="$(basename $PWD)"
# destdir="$(echo $PWD | sed "s:majstaf-en:majstaf-en/${usr}git:")"
destdir="$(echo $PWD | sed "s:majstaf_${usr}/\(.*\):majstaf_${usr}/${usr}git/\1:" | sed "s:\.config:majstaf_${usr}/${usr}git/dotfiles_${usr}/.config:")"

read -p "cp -i ./${fname} ${destdir}/${fname} ?"
cp -v ./${fname} ${destdir}/${fname}

