#! /usr/bin/env bash

git_nvol='/usr/bin/git --git-dir=/home/gregor.redelonghi/majstaf_en/en_git/en_nvol --work-tree=/c/Users/gregor.redelonghi/majstaf_en/en_staf/majvolpejprs'

echo "Push-ing to GITHUB ..."
echo "---"
${git_nvol} push en-github-nvol master

echo

echo "Push-ing to GITLAB ..."
echo "---"
${git_nvol} push en-gitlab-nvol master

