#! /usr/bin/env bash
# testing_gtgh_testpush_en
# last change: 20240531_en

# COLOR_SET="\e[1;94m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
DEST=${HOME}/majstaf_en/coding2/testing
STTS=${TMP}/testing_status
RPRT=${TMP}/testing_report
> ${STTS}
> ${RPRT}

CURRDIR=$PWD
cd ${DEST}
for DDD in $(ls -d *); do
	echo ""
	printf "${COLOR_SET}"
	echo "*** git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ${HOME}/.local/bin/ghgl_testpush_en | tee -a ${STTS}
	grep -i 'pull' ${STTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo -e "[INFO] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE!\n" >> ${RPRT}
	fi
	> ${STTS}
	cd ..
done

echo ""
printf "${COLOR_SET}"
echo "*** REPORT ***"
printf "${COLOR_RESET}"
if [ -s ${RPRT} ]; then
	cat ${RPRT}
else
	echo "[INFO] Nothing to push!"
fi
rm ${RPRT} ${STTS} 2>/dev/null

cd ${CURRDIR}

