#! /usr/bin/env bash

### Name:	drpbx-rclone-mcdn3d-sync-R-L.sh
### Author:	RgregoR
### Date:	20201111
### Decription:
### rclone copy REMOTE(d) to LOCAL(d)
### 
### 

LOCALMN=$(cygpath -w "/c/Users/gregor.redelonghi/majstaf_en/drpbx-en/ODPRTO/MCDN_d")
REMOTEMN="dropbox:ODPRTO/MCDN_d"

LOCALJV=$(cygpath -w "/c/Users/gregor.redelonghi/majstaf_en/drpbx-en/ODPRTO/home_username_majstaf_java_d")
REMOTEJV="dropbox:ODPRTO/home_username_majstaf_java_d"

LOCALMT=$(cygpath -w "/c/Users/gregor.redelonghi/majstaf_en/drpbx-en/ODPRTO/METSYS_skupno/doma")
REMOTEMT="dropbox:ODPRTO/METSYS_skupno/doma"

function update() {
    FROM=$1
    TO=$2
    echo "Updating remote ${FROM} to local ${TO}"
    /usr/local/bin/rclone -v sync ${FROM} ${TO}
    
    # dry-run
    # /usr/local/bin/rclone -v -n copy ${FROM} ${TO}
    
    if [ $? == 0 ]; then
        echo "Done."
    else
        echo "Something went wrong!"
        exit 1
    fi
}

update ${REMOTEMN} ${LOCALMN}
update ${REMOTEJV} ${LOCALJV}
update ${REMOTEMT} ${LOCALMT}
