#! /usr/bin/env bash
# 20251021 (en)
# last change 20251021

SRC="/c/Users/gregor.redelonghi/2025/_2025_1_PROJEKTI"
DST="mega_gren:ENERGETIKA/_2025_1_PROJEKTI"

if [ $# -eq 1 ] && [ "${1}" == "-y" ]; then
	yes | rclone copy --update $(cygpath -w "${SRC}") ${DST} --progress
else
	echo "[INFO] backup/copy '${SRC}' to 'MEGA.nz (mega_gren)'"
	read -p "[INFO] Confirm? "

	rclone copy --update $(cygpath -w "${SRC}") ${DST} --progress
fi


