#! /usr/bin/env bash
# filename: rbekap-DAILY-mega-gren
# 20251126 en v1
# 20251127 en v2: add final info
# last: 20251127
# ---

#v2
declare -a DESTS=("/c/Users/gregor.redelonghi/2025/_2025_1_PROJEKTI" \
                  "~/majstaf/engit" \
                  "~/majstaf/majscripts_en" \
                  "~/majstaf/majsupport_en" \
                  "~/majstaf/seznami/bookmarks-en" \
                  "/c/Users/gregor.redelonghi/Downloads/__ARHIVIRAJ")

#v1
echo "[INFO] running DAILY backup/sync to 'MEGA.nz (mega_gren)'"
rbekap-PROJEKTI-sync-mega-gren -y; echo "---" && \
rbekap-ENGIT-sync-mega-gren -y; echo "---" && \
rbekap-SCRIPTS-sync-mega-gren -y; echo "---" && \
rbekap-SUPPORT-sync-mega-gren -y; echo "---" && \
rbekap-BOOKMARKS-EN-2025-sync-mega-gren -y; echo "---" && \
rbekap-DOWNLOADS-copy-mega-gren -y

#v2
echo -e "---\n[INFO] backup/sync of:"
for DEST in "${DESTS[@]}"; do
	echo -e "\t'${DEST}'"
done
echo "to 'mega_gren:ENERGETIKA' done"
echo ""

