#! /usr/bin/env bash
# 20251021 (en)
# last change 20251021

SRC="/h/2025/_2025_podloge"
DST="mega_gren:ENERGETIKA/h_2025_podloge"

if [ $# -eq 1 ] && [ "${1}" == "-y" ]; then
	yes | rclone sync --update $(cygpath -w "${SRC}") ${DST} --progress
else
	echo "[INFO] backup/sync '${SRC}' to 'MEGA.nz (mega_gren)'"
	read -p "[INFO] Confirm? "
	rclone sync --update $(cygpath -w "${SRC}") ${DST} --progress
fi
