#! /usr/bin/env bash

SRC="/home/gregor.redelonghi/majstaf/coding2/toolbox"
DST="mega_gren:ENERGETIKA/toolbox_en"
# excludes_path="$(cygpath -w $(dirname $(realpath ${BASH_SOURCE[0]}))/excludes)"

echo "[INFO] backup/copy '${SRC}' to 'MEGA.nz (mega_gren)'"
read -p "[INFO] Confirm? "

# rclone sync --update --filter-from ${excludes_path} $(cygpath -w "${SRC}") ${DST} --progress
rclone sync --update $(cygpath -w "${SRC}") ${DST} --progress

