#! /usr/bin/env bash
# 20251021 en
# 20251218 en: += CURRYR
# last change 20251218

CURRYR=2026

SRC="/h/${CURRYR}/_${CURRYR}_podloge"
DST="mega_gren:ENERGETIKA/h_${CURRYR_podloge}_podloge"

if [ $# -eq 1 ] && [ "${1}" == "-y" ]; then
	echo "[INFO] backup/copy '${SRC}' to 'MEGA.nz (mega_gren)'"
	yes | rclone copy --update $(cygpath -w "${SRC}") ${DST} --progress
else
	echo "[INFO] backup/copy '${SRC}' to 'MEGA.nz (mega_gren)'"
	read -p "[INFO] Confirm? "
	rclone copy --update $(cygpath -w "${SRC}") ${DST} --progress
fi
