#! /usr/bin/env bash

SRC="/c/Users/gregor.redelonghi/2025/Tehnicne-zahteve_2025/Tehnicne-zahteve_2025-07"
DST="mega_gren:ENERGETIKA/Tehnicne-zahteve_2025/Tehnicne-zahteve_2025-07"

echo "[INFO] backup/sync '${SRC}' to 'MEGA.nz (mega_gren)'"
read -p "[INFO] Confirm? "

rclone sync --update $(cygpath -w "${SRC}") ${DST} --progress

