#! /usr/bin/env bash

SRC="/home/gregor.redelonghi/majstaf/engit"
DST="mega_gren:ENERGETIKA/ENGIT"

read -p "[INFO] backup/copy '${SRC}' to 'MEGA.nz (mega_gren)'"

rclone sync --update --filter-from excludes $(cygpath -w "${SRC}") ${DST} --progress

