#! /usr/bin/env bash

SRC="/h/2025/_2025_podloge"
DST="mega_gren:ENERGETIKA/h_2025_podloge"

echo "[INFO] backup/sync '${SRC}' to 'MEGA.nz (mega_gren)'"
read -p "[INFO] Confirm? "

rclone sync --update $(cygpath -w "${SRC}") ${DST} --progress
