#! /usr/bin/env bash
# filename: rbekap-DAILY-mega-gren
# 20251126 en
# last: 20251126
# ---

echo "[INFO] running DAILY backup/sync to 'MEGA.nz (mega_gren)'"
rbekap-PROJEKTI-sync-mega-gren -y; echo "---" && \
rbekap-ENGIT-sync-mega-gren -y; echo "---" && \
rbekap-SCRIPTS-sync-mega-gren -y; echo "---" && \
rbekap-SUPPORT-sync-mega-gren -y; echo "---" && \
rbekap-BOOKMARKS-EN-2025-sync-mega-gren -y; echo "---" && \
rbekap-DOWNLOADS-copy-mega-gren -y
echo ""

