#! /usr/bin/env bash

SRC="/c/Users/gregor.redelonghi/Downloads/__ARHIVIRAJ"
DST="mega_gren:ENERGETIKA/Downloads"

echo "[INFO] backup/copy '${SRC}' to 'MEGA.nz (mega_gren)'"
read -p "[INFO] Confirm? "

rclone copy --update $(cygpath -w "${SRC}") ${DST} --progress

