#! /usr/bin/env bash
# filename: engt_testpush
# last edit: 20240530_en

# COLOR_SET="\e[1;94m"
# COLOR_SET="\e[1;34m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
EDEST=${HOME}/majstaf/engit
ESTTS=${TMP}/engit_status
ERPRT=${TMP}/engit_report
> ${ESTTS}
> ${ERPRT}

CURRDIR=$PWD
cd ${EDEST}
for DDD in $(find * -maxdepth 0 -type d); do
	echo ""
	printf "${COLOR_SET}"
	echo "*** git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ~/.local/bin/ghgl_testpush_en | tee -a ${ESTTS}
	grep -i 'pull' ${ESTTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo -e "[INFO] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE!\n" >> ${ERPRT}
	fi
	> ${ESTTS}
	cd ..
done

echo ""
printf "${COLOR_SET}"
echo "*** REPORT ***"
printf "${COLOR_RESET}"
if [ -s ${ERPRT} ]; then
	cat ${ERPRT}
else
	echo "[INFO] Nothing to push!"
fi
rm ${ERPRT} ${ESTTS} 2>/dev/null

cd ${CURRDIR}

