#! /usr/bin/env bash
# filename: engt_testpush
# last edit: 20241021

# COLOR_SET="\e[1;94m"
# COLOR_SET="\e[1;34m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
HST="en"
DEST=${HOME}/majstaf_${HST}/${HST}git
STTS=${TMP}/${HST}git_status
RPRT=${TMP}/${HST}git_report
> ${STTS}
> ${RPRT}

CURRDIR=$PWD
cd ${DEST}

echo "========================================"
echo "[INFO] running engt_testpush ..."
echo "========================================"
for DDD in $(find * -maxdepth 0 -type d); do
	printf "${COLOR_SET}"
	echo "***    git testpush in: ${DDD} ..."
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ~/.local/bin/ghgl_testpush_${HST} | tee -a ${STTS}
	grep -i 'pull' ${STTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo -e "[REPORT] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE" >> ${RPRT}
	fi
	> ${STTS}
	cd ..
done

printf "${COLOR_SET}"
if [ -s ${RPRT} ]; then
	while read LINE; do
		echo "*** ${LINE} ***"
	done < ${RPRT}
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"
rm ${RPRT} ${STTS} 2>/dev/null

cd ${CURRDIR}

echo ""
