#! /usr/bin/env bash
# ghgltestpush_en
# last change: 20240228_en

rmts=( $(git remote) )

COLOR_RED="\e[1;92m"
COLOR_RESET="\e[0m"

for rmt in "${rmts[@]}"
do
	echo -n "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
	/usr/bin/git push --dry-run ${rmt} main &> status
	grep 'main' status > /dev/null
	if [[ $? -eq 0 ]]; then
		printf " ${COLOR_RED} NEED TO PUSH!!\n"
		cat status
		rm status > /dev/null
		printf "${COLOR_RESET}"
	else
		echo " nothig to push!"
		rm status > /dev/null
	fi
done

