#! /usr/bin/env bash
# filename: testing_gtghstatus_en
# 20241216: store output of commands into array instead of external file
# last change: 20241216

HST="en"
TSTDST=${HOME}/majstaf_${HST}/coding2/testing
COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"
CURRDIR=$PWD

unset msg
unset report
report=()

function get_status() {
	cmd=$1
	output=$(echo -n $(${cmd} status))
	echo $output | grep -i "git push\|untracked\|modifiedi\|deleted" > /dev/null

	if [[ $? -ne 0 ]]; then
		echo -n "[INFO] checking git status in ${DDD} ..."
		echo " no action required"
	else
		echo "---"
		printf "${COLOR_SET}"
		msg=$(echo -e "[REPORT] checking git status in ${DDD} ... NEED TO ADD and/or COMMIT\n")
		echo -e "$msg"
		printf "${COLOR_RESET}"
		readarray -t -O "${#report[@]}" report < <(echo -e "$msg")
		${cmd} status
		echo "---"
	fi
}

echo "========================================="
echo "[INFO] running testing_gtgh_status_en ..."
echo "========================================="
cd ${TSTDST}
for DDD in $(find * -maxdepth 0 -type d | grep -v "vlpprs_${HST}"); do
	cd $DDD &> /dev/null

	get_status "/usr/bin/git"
	cd ..
done

printf "${COLOR_SET}"
if [ ${#report[@]} -gt 0 ]; then
	for j in $(seq 0 $((${#report[@]} - 1))); do
		echo "*** ${report[$j]} ***"
	done
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"

cd ${CURRDIR}

echo ""

