#! /usr/bin/env bash
# testing_gtghstatus_en
# last change: 20240228_en

for DDD in $(ls -1 ~/majstaf_en/coding2/testing/); do
	echo "[INFO] Testing git status on ${DDD} ..."
	cd $DDD
	/usr/bin/git status
	cd ${HOME}
	echo -e "---\n"
done

