#! /usr/bin/env bash
# testing_gtghstatus_en
# last change: 20241021

HST="en"
TSTDST=${HOME}/majstaf_${HST}/coding2/testing
COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"
CURRDIR=$PWD
TRPRT=${TMP}/testing_report
> ${TRPRT}

function get_status() {
	cmd=$1
	OUTPUT=$(${cmd} status)

	echo $OUTPUT | grep -i "git push\|untracked\|modifiedi\|deleted" > /dev/null

	if [[ $? -ne 0 ]]; then
		echo -n "[INFO] checking git status in ${DDD} ..."
		echo " no action required"
	else
		echo "---"
		printf "${COLOR_SET}"
		printf "[REPORT] checking git status in ${DDD} ... NEED TO ADD and/or COMMIT\n" | tee -a ${TRPRT}
		printf "${COLOR_RESET}"
		${cmd} status
		echo "---"
	fi
}

echo "========================================="
echo "[INFO] running testing_gtgh_status_en ..."
echo "========================================="
cd ${TSTDST}
for DDD in $(find * -maxdepth 0 -type d | grep -v "vlpprs_${HST}"); do
	cd $DDD &> /dev/null

	get_status "/usr/bin/git"
	cd ..
done

printf "${COLOR_SET}"
if [ -s ${TRPRT} ]; then
	while read LINE; do
		echo "*** ${LINE} ***"
	done < ${TRPRT}
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"

rm ${TRPRT} 2>/dev/null
cd ${CURRDIR}

echo ""
